### ISSUE TITLE
The output svg file missing some style information.

### ISSUE THREAD

**Issue by jane00** [jaredrummler/vector2svg#1]
Thanks very much for this tool.

When I drag the svg into chorme to preview the icon.

The information shows “This XML file does not appear to have any style information associated with it. The document tree is shown below.”

And when I add style information bellow into the <svg ... > tag. It could be shown correctly. ^_^

style information：

xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink”

**Comment by jane00** [comment]
xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink"

**Comment by jaredrummler** [comment]
> When I drag the svg into chorme to preview the icon.

It sounds like you are using [this tool](http://inloop.github.io/svg2android/). That project is maintained by @inloop. https://github.com/inloop/svg2android

This is a small project to convert the android vector drawable back into a SVG. You need to run the jar from the command line/terminal to use it.

**Comment by jane00** [comment]
Thanks for your reply.
And, I'm sorry for my poor English.
I must describe the issue in a wrong way.
Using your tool, I could convert xml2svg correctly.
And I wrote a .bat file for dragging file to convert, just one line:
"

java.exe -jar vector2svg-1.1.jar %*

"

The issue I means that in the converted svg file, in the  “svg” tag, it is missing the style information for the svg file。
So, when I drag the svg file into google chrome browser,  It could not be display.
